[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "artf_licencias"
authors = [{name = "Rafael Escudero", email = "kiwi99@mail"}]
dynamic = ["version", "description"]
